"""add is_edited to message

Revision ID: 38e421b8d066
Revises: 7ff1ce10f5ff
Create Date: 2026-05-15 12:19:12.599589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e421b8d066'
down_revision: Union[str, None] = '7ff1ce10f5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_edited')
    # ### end Alembic commands ###
