"""add description to chat_rooms

Revision ID: f009cabaaeaf
Revises: 38e421b8d066
Create Date: 2026-05-15 12:31:02.018671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f009cabaaeaf'
down_revision: Union[str, None] = '38e421b8d066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'description')
    # ### end Alembic commands ###
